---
- hosts: localhost
  connection: local

  roles:
  - { role: geerlingguy.homebrew }

  tasks:
  - name: initialize rbenv
    lineinfile:
      dest: "~/.bashrc"
      regexp: "^eval \"$(rbenv init -)\""
      line:    "eval \"$(rbenv init -)\""
      state: "present"

  - name: get installed ruby versions
    command: "rbenv versions"
    register: installed_rubies

  - name: see if our target ruby is installed
    set_fact:
      ruby_installed: "{{ ruby_version }} in installed_rubies"

  - name: install ruby
    command: "rbenv install {{ ruby_version }}"
    when: not ruby_installed

  - name: "set default ruby to {{ ruby_version }}"
    command: "rbenv global {{ ruby_version }}"

  # NOTE: the gem module does not jibe with rbenv.
  # it installs but rehashing to get the executables doesn't work
  # TODO: try rbenv-default-gems as per:
  # https://medium.com/@philnash/always-install-bundler-alongside-ruby-with-rbenv-1b561a8e54f
  - name: install bundler
    command: "gem install bundler"

  - name: shim ruby executables
    command: "rbenv rehash"
